# Generated by Django 4.1.2 on 2022-11-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.IntegerField()),
                ('cant_prod', models.IntegerField()),
                ('nombre_prod', models.CharField(max_length=25)),
                ('tipo_prod', models.CharField(max_length=20)),
            ],
        ),
    ]
